# Generated by Django 4.2.1 on 2023-08-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asura', '0006_alter_token_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='kevin@gmail.com', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
