# Generated by Django 4.2.1 on 2024-03-03 12:14

import asura.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asura', '0015_alter_post_comments_count_alter_post_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default=None, null=True, upload_to=asura.models.User.profile_picture_upload_path),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
